// Objective-C API for talking to frp_lib/cmd/libfrpc_mobile Go package.
//   gobind -lang=objc frp_lib/cmd/libfrpc_mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Libfrp_H__
#define __Libfrp_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@protocol LibfrpFrpLogListener;
@class LibfrpFrpLogListener;

@protocol LibfrpFrpLogListener <NSObject>
- (NSString* _Nonnull)location;
- (void)log:(NSString* _Nullable)log;
@end

FOUNDATION_EXPORT BOOL LibfrpIsFrpcRunning(void);

FOUNDATION_EXPORT BOOL LibfrpReloadFrpc(void);

FOUNDATION_EXPORT BOOL LibfrpRunFrpc(NSString* _Nullable cfgFilePath, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void LibfrpSetFrpLogListener(id<LibfrpFrpLogListener> _Nullable l);

FOUNDATION_EXPORT BOOL LibfrpStopFrpc(NSError* _Nullable* _Nullable error);

/**
 * Version frp
 */
FOUNDATION_EXPORT NSString* _Nonnull LibfrpVersion(void);

@class LibfrpFrpLogListener;

@interface LibfrpFrpLogListener : NSObject <goSeqRefInterface, LibfrpFrpLogListener> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (NSString* _Nonnull)location;
- (void)log:(NSString* _Nullable)log;
@end

#endif
