
// Objective-C API for talking to the following Go packages
//
//	frp_lib/cmd/libfrpc_mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Libfrpc_FRAMEWORK_H__
#define __Libfrpc_FRAMEWORK_H__

#include "Libfrp.objc.h"
#include "Universe.objc.h"

#endif
